// C code generation module. Takes the IR and emits compilable C source code.
// The generated C includes a minimal runtime header with type definitions
// for GalaxC's core types (Text, Option, Result, bounds checking, etc.)

use crate::ir::*;
// Token imports removed

/// Generate a complete, self-contained C source file from an IR program.
pub fn generate(program: &IrProgram, filename: &str) -> String {
    let mut emitter = CGen::new(filename);
    emitter.emit_program(program);
    emitter.output
}

struct CGen {
    output: String,
    indent: usize,
    filename: String,
}

impl CGen {
    fn new(filename: &str) -> Self {
        CGen {
            output: String::with_capacity(8192),
            indent: 0,
            filename: filename.to_string(),
        }
    }

    fn line(&mut self, text: &str) {
        let pad = "    ".repeat(self.indent);
        self.output.push_str(&pad);
        self.output.push_str(text);
        self.output.push('\n');
    }

    fn blank(&mut self) {
        self.output.push('\n');
    }

    fn emit_program(&mut self, program: &IrProgram) {
        self.emit_header(program);
        self.emit_runtime();
        self.blank();

        // Forward declarations
        for s in &program.structs {
            self.line(&format!("typedef struct Gxc_{name} Gxc_{name};", name = s.name));
        }
        for e in &program.enums {
            self.line(&format!("typedef struct Gxc_{name} Gxc_{name};", name = e.name));
        }
        self.blank();

        // Struct definitions
        for s in &program.structs {
            self.emit_struct(s);
        }

        // Enum definitions
        for e in &program.enums {
            self.emit_enum(e);
        }

        // Constants
        for c in &program.constants {
            self.line(&format!(
                "static const {} {} = {};",
                c.c_type, c.name, c.value
            ));
        }
        if !program.constants.is_empty() {
            self.blank();
        }

        // Function forward declarations
        for f in &program.functions {
            self.emit_function_decl(f);
        }
        self.blank();

        // Function definitions
        for f in &program.functions {
            self.emit_function(f);
        }

        // Entry point
        self.emit_main(program);
    }

    fn emit_header(&mut self, _program: &IrProgram) {
        self.line("/*");
        self.line(&format!(" * Generated by GalaxC compiler from {}", self.filename));
        self.line(" * DO NOT EDIT - this file is automatically generated.");
        self.line(" *");
        self.line(" * GalaxC: Code that survives the void.");
        self.line(" */");
        self.blank();
    }

    fn emit_runtime(&mut self) {
        // Emit the minimal runtime support code that all GalaxC programs need
        self.line("#include <stdio.h>");
        self.line("#include <stdlib.h>");
        self.line("#include <stdint.h>");
        self.line("#include <stdbool.h>");
        self.line("#include <string.h>");
        self.line("#include <math.h>");
        self.blank();

        self.line("/* GalaxC Runtime Support */");
        self.blank();

        // Text type
        self.line("typedef struct GxcText {");
        self.indent += 1;
        self.line("const char* data;");
        self.line("int64_t len;");
        self.indent -= 1;
        self.line("} GxcText;");
        self.blank();

        self.line("static GxcText gxc_text_from(const char* s) {");
        self.indent += 1;
        self.line("GxcText t;");
        self.line("t.data = s;");
        self.line("t.len = (int64_t)strlen(s);");
        self.line("return t;");
        self.indent -= 1;
        self.line("}");
        self.blank();

        self.line("static GxcText gxc_text_concat(GxcText a, GxcText b) {");
        self.indent += 1;
        self.line("int64_t total = a.len + b.len;");
        self.line("char* buf = (char*)malloc((size_t)(total + 1));");
        self.line("if (!buf) { fprintf(stderr, \"GalaxC: allocation failure\\n\"); abort(); }");
        self.line("memcpy(buf, a.data, (size_t)a.len);");
        self.line("memcpy(buf + a.len, b.data, (size_t)b.len);");
        self.line("buf[total] = '\\0';");
        self.line("GxcText t;");
        self.line("t.data = buf;");
        self.line("t.len = total;");
        self.line("return t;");
        self.indent -= 1;
        self.line("}");
        self.blank();

        self.line("static bool gxc_text_eq(GxcText a, const char* b) {");
        self.indent += 1;
        self.line("return strcmp(a.data, b) == 0;");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Console output
        self.line("typedef struct GxcConsole { int _unused; } GxcConsole;");
        self.line("static GxcConsole console;");
        self.blank();

        self.line("static void GxcConsole_write(GxcText t) {");
        self.indent += 1;
        self.line("printf(\"%.*s\\n\", (int)t.len, t.data);");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Bounds checking
        self.line("static void gxc_bounds_panic(int64_t index, int64_t len) {");
        self.indent += 1;
        self.line("fprintf(stderr, \"GalaxC: index %lld out of bounds (length %lld)\\n\",");
        self.line("        (long long)index, (long long)len);");
        self.line("abort();");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Checked arithmetic
        self.line("static int64_t gxc_checked_add(int64_t a, int64_t b) {");
        self.indent += 1;
        self.line("int64_t result;");
        self.line("#if defined(__GNUC__) || defined(__clang__)");
        self.line("if (__builtin_add_overflow(a, b, &result)) {");
        self.line("    fprintf(stderr, \"GalaxC: integer overflow in addition\\n\");");
        self.line("    abort();");
        self.line("}");
        self.line("#else");
        self.line("result = a + b;");
        self.line("#endif");
        self.line("return result;");
        self.indent -= 1;
        self.line("}");
        self.blank();

        self.line("static int64_t gxc_checked_mul(int64_t a, int64_t b) {");
        self.indent += 1;
        self.line("int64_t result;");
        self.line("#if defined(__GNUC__) || defined(__clang__)");
        self.line("if (__builtin_mul_overflow(a, b, &result)) {");
        self.line("    fprintf(stderr, \"GalaxC: integer overflow in multiplication\\n\");");
        self.line("    abort();");
        self.line("}");
        self.line("#else");
        self.line("result = a * b;");
        self.line("#endif");
        self.line("return result;");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Math constants
        self.line("#ifndef M_PI");
        self.line("#define M_PI 3.14159265358979323846");
        self.line("#endif");
        self.blank();

        // Display helpers for numeric types
        self.line("static GxcText gxc_int_display(int64_t v) {");
        self.indent += 1;
        self.line("char buf[32];");
        self.line("snprintf(buf, sizeof(buf), \"%lld\", (long long)v);");
        self.line("char* s = (char*)malloc(strlen(buf) + 1);");
        self.line("strcpy(s, buf);");
        self.line("GxcText t; t.data = s; t.len = (int64_t)strlen(s);");
        self.line("return t;");
        self.indent -= 1;
        self.line("}");
        self.blank();

        self.line("static GxcText gxc_float_display(double v) {");
        self.indent += 1;
        self.line("char buf[64];");
        self.line("snprintf(buf, sizeof(buf), \"%.6f\", v);");
        self.line("char* s = (char*)malloc(strlen(buf) + 1);");
        self.line("strcpy(s, buf);");
        self.line("GxcText t; t.data = s; t.len = (int64_t)strlen(s);");
        self.line("return t;");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // GXC_NONE sentinel
        self.line("#define GXC_NONE 0");
        self.blank();

        // Propagation macro
        self.line("#define GXC_PROPAGATE(expr) (expr) /* simplified propagation */");
        self.blank();
    }

    fn emit_struct(&mut self, s: &IrStruct) {
        self.line(&format!("struct Gxc_{} {{", s.name));
        self.indent += 1;
        for field in &s.fields {
            self.line(&format!("{} {};", field.c_type, field.name));
        }
        self.indent -= 1;
        self.line("};");
        self.blank();
    }

    fn emit_enum(&mut self, e: &IrEnum) {
        // Emit tag constants
        for variant in &e.variants {
            self.line(&format!(
                "#define GXC_TAG_{} {}",
                variant.name.to_uppercase(),
                variant.tag
            ));
        }
        self.blank();

        // Emit the tagged union struct
        self.line(&format!("struct Gxc_{} {{", e.name));
        self.indent += 1;
        self.line("int32_t tag;");
        self.line("union {");
        self.indent += 1;
        for variant in &e.variants {
            if variant.fields.is_empty() {
                self.line(&format!("int _{}; /* unit variant */", variant.name.to_lowercase()));
            } else {
                self.line(&format!("struct {{"));
                self.indent += 1;
                for field in &variant.fields {
                    self.line(&format!("{} {};", field.c_type, field.name));
                }
                self.indent -= 1;
                self.line(&format!("}} {};", variant.name.to_lowercase()));
            }
        }
        self.indent -= 1;
        self.line("} data;");
        self.indent -= 1;
        self.line("};");
        self.blank();
    }

    fn emit_function_decl(&mut self, f: &IrFunction) {
        if f.body.is_empty() {
            return; // Skip declarations for extern functions without bodies
        }
        let params = self.format_params(&f.params);
        let ret = if f.return_type == "void" {
            "void"
        } else {
            &f.return_type
        };
        self.line(&format!("static {ret} gxc_{name}({params});", name = f.name));
    }

    fn emit_function(&mut self, f: &IrFunction) {
        let params = self.format_params(&f.params);
        let ret = if f.return_type == "void" {
            "void"
        } else {
            &f.return_type
        };
        self.blank();
        self.line(&format!("static {ret} gxc_{name}({params}) {{", name = f.name));
        self.indent += 1;
        for stmt in &f.body {
            self.emit_stmt(stmt);
        }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_stmt(&mut self, stmt: &IrStmt) {
        match stmt {
            IrStmt::VarDecl { name, c_type, init } => {
                if let Some(init) = init {
                    self.line(&format!("{c_type} {name} = {init};"));
                } else {
                    self.line(&format!("{c_type} {name};"));
                }
            }
            IrStmt::Assign { target, value } => {
                self.line(&format!("{target} {value};"));
            }
            IrStmt::Return { value } => {
                if let Some(v) = value {
                    self.line(&format!("return {v};"));
                } else {
                    self.line("return;");
                }
            }
            IrStmt::Expr { expr } => {
                self.line(&format!("{expr};"));
            }
            IrStmt::If { condition, then_body, else_body } => {
                self.line(&format!("if ({condition}) {{"));
                self.indent += 1;
                for s in then_body {
                    self.emit_stmt(s);
                }
                self.indent -= 1;
                if !else_body.is_empty() {
                    self.line("} else {");
                    self.indent += 1;
                    for s in else_body {
                        self.emit_stmt(s);
                    }
                    self.indent -= 1;
                }
                self.line("}");
            }
            IrStmt::While { condition, body } => {
                self.line(&format!("while ({condition}) {{"));
                self.indent += 1;
                for s in body {
                    self.emit_stmt(s);
                }
                self.indent -= 1;
                self.line("}");
            }
            IrStmt::For { init, condition, update, body } => {
                self.line(&format!("for ({init}; {condition}; {update}) {{"));
                self.indent += 1;
                for s in body {
                    self.emit_stmt(s);
                }
                self.indent -= 1;
                self.line("}");
            }
            IrStmt::Block { body } => {
                self.line("{");
                self.indent += 1;
                for s in body {
                    self.emit_stmt(s);
                }
                self.indent -= 1;
                self.line("}");
            }
            IrStmt::Break => self.line("break;"),
            IrStmt::Continue => self.line("continue;"),
            IrStmt::Comment { text } => self.line(&format!("/* {text} */")),
            IrStmt::Raw { code } => self.line(code),
        }
    }

    fn emit_main(&mut self, program: &IrProgram) {
        self.blank();
        self.line("int main(int argc, char** argv) {");
        self.indent += 1;
        self.line("(void)argc; (void)argv;");

        if let Some(ref entry) = program.entry_point {
            self.line(&format!("gxc_{entry}();"));
        } else {
            self.line("fprintf(stderr, \"GalaxC: no launch() entry point found\\n\");");
            self.line("return 1;");
        }

        self.line("return 0;");
        self.indent -= 1;
        self.line("}");
    }

    fn format_params(&self, params: &[IrParam]) -> String {
        if params.is_empty() || (params.len() == 1 && params[0].name == "self") {
            return "void".to_string();
        }
        params
            .iter()
            .filter(|p| p.name != "self")
            .map(|p| format!("{} {}", p.c_type, p.name))
            .collect::<Vec<_>>()
            .join(", ")
    }
}
